Basic Scene Kit
DCC-Lab/PyTissueOptics pull request #39
Opened 2022-02-12 17:57 UTC by PyMarc2

Regrouping geometrical logic and scene/objects management in 3d space into a separate folder, completely independant from the physics, has been a necessity for the future of the project and major relief for the developpers.

Here we present the first "draft" of our python scene kit. 
For now, It allows for:
- Has the main geometrical framework basics: `Vector`, `Polygon`, `SurfaceCollection`, which allow for the creation of 3D objects, meshes, and on which the module is based for now.
- Creation `Solid` objects with various shapes: `Cuboid`, `Cube`, `Sphere`, `Ellipsoid`.
- Allows the stacking of `Cuboid` objects that merges the interface into a single surface.
- Apply `Transforms` on `Solid`. `Solid().translateTo`, `Solid().translateBy`, `Solid().rotate`.
- A `Loader which allows to load Wavefront .obj 3d objects as an object defined into our python objects.
- A Basic implementation of a `Viewer`, which allows for these 3D objects to be visualized

Here are some examples that can show what it does for now.

Future updates are coming in the next week, such as:
- Managing `Solids` in `Solids`
- Basic Raytracing (`IntersectionFinder`)
- Implementing `SolidGroups` to compensate for the non-node oriented approach, for complex objects such as lenses
- Implementing a `Scene` which is more than a List[Solid]
- Implementing `KDTree` for the scene
- Improved `Viewer` features

2022-03-05 15:27 UTC, dccote commented on pytissueoptics/scene/solids/cuboid.py
> +    def _fromStackResult(cls, stackResult: StackResult) -> 'Cuboid':
Pourquoi les underscores?

2022-03-05 15:34 UTC, dccote requested changes
Plusieurs modifications au moins pour le style a faire tout de suite ou a justifier.  Je regarde le design et le fonctionnement bientot.

2022-03-05 15:34 UTC, dccote commented on pytissueoptics/scene/geometry/polygon.py
> -    def _computeNormal(self):
Vous allez m'expliquer chaque underscore dans un nom de fonction ou d'une variable. Pourquoi faire ca?

2022-03-05 15:34 UTC, dccote commented on pytissueoptics/scene/loader/parsers/obj/objParser.py
> +        self._objects[self._currentObjectName].surfaces[self._currentSurfaceName].polygons.append(faceIndices)
Si vous avez defini @property objects comme etant _objects, alors prenez la @property, n'accedez pas directement a la variable.

2022-03-05 15:34 UTC, dccote commented on pytissueoptics/scene/loader/parsers/obj/objParser.py
> +        self._objects[self._currentObjectName].surfaces[self._currentSurfaceName].polygons.append(faceIndices)
Il y en a partout et ça me rend dingue: si vous voulez cacher les variables avec _vertices par exemple et definir un @property, alors utilisez la partout. Sinon, vous avez tout fait ca pour rien.

2022-03-05 15:34 UTC, dccote commented on pytissueoptics/scene/solids/stack/cuboidStacker.py
> +class CuboidStacker:
Un Cuboid, c'est clairement une "Box".

2022-03-05 15:46 UTC, JLBegin commented on pytissueoptics/scene/geometry/polygon.py
> -    def _computeNormal(self):
C'est une convention pour déclarer des variables ou méthodes privées/internes. 

Et même si on défini un getter publique, on ne l'utilise pas dans la classe en soi. Il est juste là pour répondre à une autre classe qui doit intéragir avec. 

Cette convention permet de bien isoler l'interface de chaque classe. Séparer le bruit interne de l'API.

2022-03-09 18:18 UTC, dccote commented on pytissueoptics/scene/geometry/polygon.py
> -    def _computeNormal(self):
Ok, mettons que j'accepte.

2022-03-17 13:41 UTC, merged